### PR TITLE
Refactor Keller 9Lx pressure sensor driver

### PR DESCRIPTION
**Pull request by hidmic**
Precisely what the title says. This patch:

- Sets timeouts for each send/recv operation
- Supports automatic reconnections

Plus an overall code cleanup. 

**It needs thorough testing**, as I don't have the hardware at hand.

### CODE REVIEW

**Comment by hidmic** [comment]
> It needs thorough testing, as I don't have the hardware at hand.

@ChrisScianna I'll need your help with this.

**Review by patapufate — APPROVED** [review]
I did a double check on the Diagnostics msgs (Stale, Stagnated and Threshold reached) and are OK
LGTM.

**Comment by ChrisScianna** [comment]
I'll test it out today and let you know. Thanks

**Comment by ChrisScianna** [comment]
Tested and LGTM

**Pull request merged**
