### PR TITLE
Make sure fault codes and diagnostic levels are correct.

### PR DESCRIPTION
**Pull request by hidmic**
# Description

This patch reviews diagnostic levels and fault codes, making sure these match the specs.

## Type of change

Please mark options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The code builds clean without any errors or warnings
- [ ] Unit tests are passing
- [x] Linter tests are passing

# How To Test

Run system testbed on the vehicle:

```sh
catkin_make run_tests_system_testbed
```

### CODE REVIEW

**Comment by hidmic** [comment]
A cleanup I did a couple weeks ago but did not submit !

**Review by patapufate — APPROVED** [review]
LGTM!

**Comment by hidmic** [comment]
Needs https://github.com/ekumenlabs/qna-mkx/pull/176 and connected PRs.

**Comment by hidmic** [comment]
Needs https://github.com/ChrisScianna/ROS-Underwater-RnD/pull/120 and connected PRs.

**Comment by hidmic** [comment]
Alright, now it is correct. @patapufate PTAL !

**Review by patapufate — APPROVED** [review]
LGTM!

**Pull request merged**
