### PR TITLE
Merge inputs_to_ins package into ixblue_c3_ins package

### PR DESCRIPTION
**Pull request by hidmic**
# Description

This patch merges `inputs_to_ins` Python node and launch file into the `ixblue_c3_ins` package.

# Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The code builds clean without any errors or warnings
- [ ] Unit tests are passing
- [ ] Linter tests are passing

# How To Test

TBD

### CODE REVIEW

**Comment by hidmic** [comment]
@ChrisScianna I have to say the script is a bit unusual (e.g. setting parameters before initializing the node). Does it work?

**Comment by ChrisScianna** [comment]
Ya it started as a test.py file to see if I could properly send the data to the INS and very quickly was converted to the ROS version so probably janky. It does surprisingly work though. We can move the parameters around now though.

**Comment by hidmic** [comment]
> It does surprisingly work though. 

It's not a top priority, so I'll just get it to terminate gracefully. We can revamp it later on. See https://github.com/ChrisScianna/ROS-Underwater-RnD/pull/119/commits/1605fcd4ea5fb710d5595852e7e8fcc675044ae4.

**Review by patapufate — APPROVED** [review]
LGTM

**Comment by hidmic** [comment]
@ChrisScianna keep me posted about hardware hook ups.

**Review by patapufate — APPROVED** [review]
LGTM

**Review by ChrisScianna — APPROVED** [review]
Looks good

**Comment by hidmic** [comment]
Ok, let's not allow this to rot. I'll merge. We can do hardware testing in the future.

**Pull request merged**
