### PR TITLE
Revamp mission_control BT behaviors 

### PR DESCRIPTION
**Pull request by hidmic**
# Description

This patch updates `mission_control` behaviors, unifying implementations, enabling basic introspection, delegating timeouts to (built-in) decorators.

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] The code builds clean without any errors or warnings
- [x] Unit tests are passing
- [x] Linter tests are passing

# How To Test

TBD

### CODE REVIEW

**Review by patapufate — APPROVED** [review]
LGTM

**Comment by hidmic** [comment]
Alright, rebased to bring #116 changes in. All tests are passing now but one, the one related to the `jaus_ros_bridge`, which IMHO has to be rewritten to use the `MissionInterface` helper class.

**Review by patapufate — APPROVED** [review]
LGTM

**Comment by patapufate** [comment]
Moving forward, in the interest of time.

**Pull request merged**
